language: node_js
node_js:
  - "10"
sudo: false

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: always

install:
  - yarn
script:
  - yarn lint
  - yarn test
  - yarn coveralls
after_success:
  - yarn build:www
